### PR TITLE
french_translation

### PR DESCRIPTION
**Pull request by furynick**
Add french dictionnary

### CODE REVIEW

**Comment by jbostoen** [comment]
Thanks @furynick !

How do you like this extension so far?

**Comment by furynick** [comment]
The extension looks good but there's an issue with inputs and CI ports are still static text but I don't know if it can be linked to devices defined ports.

**Comment by furynick** [comment]
Moreover, the itop-endusers-devices dependency is a constraint, I plan tu use iTop with this extension in a professionnal only project and there's no enduser devices so it's not enabled on production iTop.

**Comment by jbostoen** [comment]
As for the graphics: is it simply an issue of not enough room to properly show all the fields?

**Comment by furynick** [comment]
Well, it seems you're right, I have the same issue with standard "device to network" form when I reduce the browser window.

**Comment by jbostoen** [comment]
Thanks for confirming :)

You could either show less fields, or temporarily collapse the left menu, decrease zoom level of your browser, ...

**Pull request merged**
